<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJyI6WcC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJyI6WcC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJyI6WcC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJyI6WcC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJyI6WcC\App_KernelDevDebugContainer([
    'container.build_hash' => 'JyI6WcC',
    'container.build_id' => 'fa8adbd7',
    'container.build_time' => 1615856551,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJyI6WcC');
